name: Create Archive
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: papeloto/action-zip@v1
      with:
        files: scenefiles/
        dest: MuppetsTeamsTogetherScene.zip
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "MuppetsTeamsTogetherScene.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
