name: Create Archive
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: 'scenefiles'
        filename: 'MuppetsTeamsTogetherScene.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "MuppetsTeamsTogetherScene.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
